import { StyleSheet } from "react-native";

/** Palette douce alignée sur l’écran d’accueil (jaune pastel, bleu ciel, touches chaudes). */
export const T = {
  bg: "#fff8ef",
  bgAlt: "#e9f7fe",
  card: "#ffffff",
  cardBorder: "#ffe4b5",
  cardShadow: "rgba(45, 80, 120, 0.08)",
  ink: "#2a2540",
  inkMuted: "#5c5678",
  accent: "#4152c9",
  accentSoft: "#6878e6",
  sun: "#ffc93c",
  sunBorder: "#f6b629",
  mint: "#7dcc9b",
  mintDark: "#2d6b4e",
  sky: "#79cbdc",
  coral: "#ff8f7a",
  good: "#22a66c",
};

export const warmStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: T.bg },
  screenAlt: { flex: 1, backgroundColor: T.bgAlt },
  pad: { padding: 18, gap: 14 },
  heroEmoji: { fontSize: 42, textAlign: "center", marginBottom: 4 },
  title: { fontSize: 26, fontWeight: "900", color: T.ink, letterSpacing: -0.5 },
  titleLight: { fontSize: 24, fontWeight: "800", color: "#0f3460" },
  subtitle: { fontSize: 15, color: T.inkMuted, lineHeight: 22 },
  sectionTitle: { fontSize: 17, fontWeight: "800", color: T.ink, marginTop: 6 },
  hint: { fontSize: 13, color: T.inkMuted, lineHeight: 20 },
  card: {
    backgroundColor: T.card,
    borderRadius: 18,
    padding: 16,
    borderWidth: 2,
    borderColor: T.cardBorder,
    gap: 8,
  },
  cardLift: {
    shadowColor: "#2d4078",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  input: {
    borderWidth: 2,
    borderColor: "#e8ddcc",
    backgroundColor: "#fffdfb",
    borderRadius: 14,
    padding: 14,
    fontSize: 16,
    color: T.ink,
  },
  inputKid: {
    borderWidth: 2,
    borderColor: T.sunBorder,
    backgroundColor: "#fffefb",
    borderRadius: 16,
    padding: 14,
    fontSize: 17,
    color: T.ink,
  },
  btnSun: {
    backgroundColor: T.sun,
    borderRadius: 16,
    paddingVertical: 15,
    paddingHorizontal: 18,
    alignItems: "center",
    borderWidth: 2,
    borderColor: T.sunBorder,
  },
  btnSunText: { color: "#3d3d3d", fontWeight: "900", fontSize: 17 },
  btnPrimary: {
    backgroundColor: T.accent,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  btnPrimaryText: { color: "#fff", fontWeight: "800", fontSize: 16 },
  btnSoft: {
    backgroundColor: T.accentSoft,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    marginTop: 4,
  },
  btnSky: {
    backgroundColor: T.sky,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  pillRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  pill: {
    backgroundColor: "rgba(121, 203, 220, 0.35)",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "#a8dfe8",
  },
  pillActive: {
    backgroundColor: T.accent,
    borderColor: T.accent,
  },
  tabBar: { flexDirection: "row", gap: 8, marginBottom: 8 },
  tab: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.7)",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#e0e8f5",
  },
  tabOn: {
    backgroundColor: T.sun,
    borderColor: T.sunBorder,
  },
  tabText: { fontWeight: "800", fontSize: 14, color: T.inkMuted },
  tabTextOn: { color: T.ink },
  doneDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: T.good,
    marginLeft: 6,
  },
  tierBadge: {
    backgroundColor: "#eef7ff",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#c9ddf5",
  },
  tierText: { fontWeight: "900", fontSize: 13, color: T.accent },
  chipGreen: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(34, 166, 108, 0.12)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  kidSecondaryBtn: {
    backgroundColor: "#fdeedc",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: "center",
    marginTop: 10,
    borderWidth: 2,
    borderColor: "#f4cfa8",
  },
  blockFun: {
    backgroundColor: "#f0f7ff",
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d4e5ff",
  },
});
